version: '3.8'

services:
  rtsp-to-webrtc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtsp_to_webrtc_app
    ports:
      - "8990:8990"
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output
      - ./streams:/app/streams
      - ./logs:/app/logs
      - ./src:/app/src
      - ./static:/app/static
      - ./.env:/app/.env
    # devices:
    #   - /dev/video0:/dev/video0  # Mapear dispositivo de cámara (Linux)
    #   - /dev/video1:/dev/video1  # Mapear dispositivos adicionales si existen (Linux)
    # Nota: En Windows/WSL2 el acceso a webcam se hace desde el navegador con getUserMedia; el contenedor no necesita /dev/video*
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - APP_HOST=0.0.0.0
      - APP_PORT=8990
      - TZ=America/Bogota
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - USE_GPU=true
    gpus: all
    restart: unless-stopped
    privileged: true  # Necesario para acceso a dispositivos de hardware
    networks:
      - rtsp-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request,json; resp=urllib.request.urlopen('http://localhost:8990/health'); data=json.load(resp); sys.exit(0 if data.get('status')=='healthy' else 1)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servicio opcional para base de datos si se necesita persistencia
  # postgres:
  #   image: postgres:15
  #   container_name: rtsp_webrtc_db
  #   environment:
  #     POSTGRES_DB: rtsp_webrtc
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - rtsp-network

  # Servicio opcional para Redis si se necesita cache
  # redis:
  #   image: redis:7-alpine
  #   container_name: rtsp_webrtc_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - rtsp-network
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis_data:/data

# Configuración de red
networks:
  rtsp-network:
    driver: bridge

# volumes:
#   postgres_data:
#   redis_data: